### ISSUE TITLE
broken with pylint 2.12

### ISSUE THREAD

**Issue by ghost** [mxmeinhold/pylint-fixme-info#2]
I just started using this and I agree with everything that has been said in https://github.com/mxmeinhold/pylint-fixme-info/issues/1#issue-854023160 :)

When upgrading pylint to 2.12.x I get the following error:

```
  File "[...]/venv/lib/python3.10/site-packages/pylint_fixme_info/__init__.py", line 8, in <module>
    from pylint.message import MessagesHandlerMixIn
ImportError: cannot import name 'MessagesHandlerMixIn' from 'pylint.message' ([...]/venv/lib/python3.10/site-packages/pylint/message/__init__.py)
```

**Comment by mxmeinhold** [comment]
Thanks!

Fixed in [v1.0.3](https://pypi.org/project/pylint-fixme-info/1.0.3/)

**Comment by ghost** [comment]
Thank you! :)
